export const newsandupdates = [
    {
        id: 1,
        cover_image: "/mscpictures/May222024/featured_photo1.jpg",
        date: 'May 22, 2024',
        headline: 'Fr. Roger’s Visit in MSC Center for the Poor and CEPAGCO communities',
        description: `Fr. Roger Purcell, msc is the Director of the MSC Mission Office Australia. He visited the Philippines last May 6-20, 2024 to check and monitor some projects supported by the MO Australia. He was also able to meet some collabotators, partners and beneficiaries of the projects and discussed matters to intensify our partnership with them. We would like to thank Fr. Roger and the MO Australia for this opportunity, to be with us and the people who have been part of the Mission Office over the years. We also thank all the communities who helped us in preparing and organizing Fr. Roger’s visit. `
        ,
        hyperlink: '',
        featured_photo_2: "/mscpictures/May222024/featured_photo2.jpg",
        featured_photo_3: "/mscpictures/May222024/featured_photo3.jpg",
    },
    {
        id: 2,
        cover_image: "/mscpictures/May142024/featured_photo1.jpg",
        date: 'May 14, 2024',
        headline: 'Safeguard Orientation',
        description: `Safeguarding Orientation conducted by Fr. James Espuerta, msc, MSC Phil. Province Safeguarding Incharge, held at MSC Center for the Poor in Butuan last April 26, 2024. The activity was attended by the MSC CFTP staff, scholars and some volunteers. The MSC Center is a working arm of the MSC Phil. Province established in 2018. This grassroot organization advocates to taking care of the well-being of the people and the environment by providing services to the community such as scholarship program, clean water projects, livelihood, outreach program and emergency response. Meanwhile, the MSC Center for the Poor Agriculture Cooperative (CEPAGCO) dedicated to support environmental programs, livelihood of the local farmers for food sustainability and security, promote cooperativism and community building. It was established in 2020 in the midst of the global pandemic. Today, the MSC CEPAGCO has been growing its membership and has impacted many lives of the people in different communities`,
        hyperlink: '',
        featured_photo_2: "/mscpictures/May142024/featured_photo2.jpg",
        featured_photo_3: "/mscpictures/May142024/featured_photo3.jpg",
        featured_photo_4: "/mscpictures/May142024/featured_photo4.jpg",
        
    },
    {   
        id: 3,
        cover_image: "/mscpictures/Feb242024/featured_photo1.jpg",
        date: 'February 24, 2024',
        headline: 'Help Mindanao Project',
        description: 'The MSC Center for the Poor together with the MSC CEPAGCO conducted a relief operation to the flood affected families in San Diego and Sabang Culi, San Luis, Agusan del Sur. A total of 100 families have benefited the project.',
        hyperlink: '',
        featured_photo_2: "/mscpictures/Feb242024/featured_photo2.jpg",
        featured_photo_3: "/mscpictures/Feb242024/featured_photo3.jpg",
        featured_photo_4: "/mscpictures/Feb242024/featured_photo4.jpg",
        featured_photo_5: "/mscpictures/Feb242024/featured_photo5.jpg"
    },
    {
        id: 4,
        cover_image: "/mscpictures/Jan182024/featured_photo1.jpg",
        date: 'January 18, 2024',
        headline: 'Relief Distribution',
        description: 'The MSC Mission Office through the MSC Center for the Poor - Butuan conducted a relief distribution to the families who were affected by fire in Villa Kananga, Butuan City. ',
        hyperlink: '',
        featured_photo_2: "/mscpictures/Jan182024/featured_photo2.jpg",
        featured_photo_3: "/mscpictures/Jan182024/featured_photo3.jpg",
        featured_photo_4: "/mscpictures/Jan182024/featured_photo4.jpg",
        featured_photo_5: "/mscpictures/Jan182024/featured_photo5.jpg"
    },
    {
      id: 5,
      cover_image: "/mscpictures/May22202402/featured_photo1.jpg",
      date: 'May 22, 2024',
      headline: ' Fr. Roger visits San Luis Lumad Community High School',
      description: 'The San Luis Lumad Community High School is an MSC-administered school located in Brgy. Poblacion, San Luis, Agusan del Sur. The school was established in 1996 with the mission to help the indigineous students finish their secondary education. The school also promotes in preserving their indigenous values and culture and upholds their social, economic and cultural rights. Presently, more than 70 students are enrolled in the said lumad school.',
      hyperlink: '',
      featured_photo_2: "/mscpictures/May22202402/featured_photo2.jpg",
      featured_photo_3: "/mscpictures/May22202402/featured_photo3.jpg",
      featured_photo_4: "/mscpictures/May22202402/featured_photo4.jpg",
      featured_photo_5: "/mscpictures/May22202402/featured_photo5.jpg"
    },
    {
      id: 6,
      cover_image: "/mscpictures/Dec2021/featured_photo1.jpg",
      date: 'January 18, 2024',
      headline: ' Typhoon Odette Housing Project in Bayagnan Island, Surigao City',
      description: 'In December 2021, the country was again struck by a super typhoon that left many of our countrymen devastated and homeless. One of the most affected areas was Surigao Province, particularly the island communities of Surigao City. Since communication and electricity were down, it took us days to learn about the situation on Bayagnan Island, where we do our mission and apostolate. But despite the tough situation after the typhoon, the MSC, through the efforts of Our Lady of Peace and Good Voyage Parish and other MSC mission partners, was still able to conduct numerous relief operations in the affected communities in Surigao. On March 23, 2022, the MSC Typhoon Odette Housing Project started. And with the help of our community leaders, who dedicated their time and effort, the implementation of the project was right on schedule. And finally, two months after the construction began, on May 25, 2022, the 129 newly constructed houses were blessed by Msgr. Edito Alcala, DCS, together with the MSC Surigao District fathers. The families are so grateful for the help and support that the MSC fathers have given them. They promised that they would take good care of their new home, and they also hope and pray that God will continuously bless us so that we can be able to bless others. ',
      hyperlink: '',
      featured_photo_2: "/mscpictures/Dec2021/featured_photo2.jpg",
      featured_photo_3: "/mscpictures/Dec2021/featured_photo3.jpg",
      featured_photo_4: "/mscpictures/Dec2021/featured_photo4.jpg",
      featured_photo_5: "/mscpictures/Dec2021/featured_photo5.jpg",
      featured_photo_6: "/mscpictures/Dec2021/featured_photo6.jpg"
  },
  {
    id: 7,
    cover_image: "/mscpictures/Nov162020/featured_photo1.jpg",
    date: 'November 16, 2020',
    headline: 'Typhoon Ulysses Mission Response in Cagayan & Rizal Province',
    description: `After a super typhoon hit the country, another typhoon (Typhoon Ulysses) lashed the main island of Luzon on November 16, 2020. More than 1 million families were devastated and many livelihood were destroyed. The most affected areas were recorded in the province of Metro Manila (Marikina area), Rizal and Cagayan Valley where houses were ravaged by flood. The Missionaries of the Sacred Heart (MSC) Philippine Province through the MSC Mission Office Philippines, Inc. organized another Call or Donations campaign to help the typhoon affected families. Through the donations, the MSC Mission Office was able to send more than 400 sacks of rice, boxes of grocery items and clothing materials to our mission partners, Office of the Vice-President (OVP) and Association of Major Religious Superiors of the Philippines (AMRSP).  Our mission partners, then, conducted a relief distributions to the most affected areas in the country. 
    
    We would like to thank all the people who took part of this mission especially to all the donors and generous people who helped us raise funds for the project. And to our mission partners, the OVP and AMRSP, thank you for organizing and facilitating the relief distribution activity. In behalf of the MSC Mission Office and all the beneficiaries, "Maraming Salamat Po!"`,
    hyperlink: '',
    featured_photo_2: "/mscpictures/Nov162020/featured_photo2.jpg",
    featured_photo_3: "/mscpictures/Nov162020/featured_photo3.jpg",
    featured_photo_4: "/mscpictures/Nov162020/featured_photo4.jpg",
    featured_photo_5: "/mscpictures/Nov162020/featured_photo5.jpg",
    featured_photo_6: "/mscpictures/Nov162020/featured_photo6.jpg"
 },
 {
    id: 8,
    cover_image: "/mscpictures/Dec302024/featured_photo1.jpg",
    date: 'December 30, 2024',
    headline: 'Paskong Handog: A Christmas Noche Buena Basket Project',
    description: `The Christmas season is a time of love, generosity, and togetherness—a season where the spirit of giving shines the brightest. This year, the Missionaries of the Sacred Heart (MSC), through the MSC Mission Office, embarked on a heartfelt mission to bring joy to families in need through the "Paskong Handog: A Christmas Noche Buena Basket Project.`,
    hyperlink: '',
    featured_photo_2: "/mscpictures/Dec302024/featured_photo2.jpg",
    featured_photo_3: "/mscpictures/Dec302024/featured_photo3.jpg",
    featured_photo_4: "/mscpictures/Dec302024/featured_photo4.jpg",
 },
 {
    id: 9,
    cover_image: "/mscpictures/May202024/featured_photo1.jpg",
    date: 'May 20, 2024',
    headline: 'The Head of MSC Mission Office Australia meets with the Board of Trustees of MSC Mission Office Philippines.',
    description: `The Head of MSC Mission Office Australia meets with the Board of Trustees of MSC Mission Office Philippines.`,
    hyperlink: '',
    featured_photo_2: "/mscpictures/May202024/featured_photo2.jpg",
    featured_photo_3: "/mscpictures/May202024/featured_photo3.jpg",
 },
 {
    id: 10,
    cover_image: "/mscpictures/Feb122025/featured_photo1.jpg",
    date: 'February 12, 2025',
    headline: 'MSC Mission Office Receives Generous Grant for Calamity Relief',
    description: `The MSC Mission Office is deeply grateful to the Filipino Apostolate of Union County for their generous grant of $5,738, which will be used to provide vital support to communities affected by recent calamities. This funding will help us reach those in need with essential resources and aid, bringing hope and relief during difficult times. We are incredibly thankful for this partnership and the opportunity to work together to serve those most vulnerable in our communities.`,
    hyperlink: '',
 },
 {
    id: 11,
    cover_image: "/mscpictures/Mar132024/featured_photo1.jpg",
    date: 'March 13, 2024',
    headline: 'Feeding Program at Libis Baesa Elementary School',
    description: `The MSC Center for the Poor is dedicated to making a difference in the lives of children through its Feeding Program in Libis Baesa, ensuring that young learners receive nutritious meals while fostering a sense of community and care. This initiative would not be possible without the selfless dedication of our volunteer cooks, the Principal of Libis Baesa Elementary School, Teacher Myrna, the MSC Brothers, Chapel Presidents, Fr. Gab, and Fr. Sam.`,
    hyperlink: '',
    featured_photo_2: "/mscpictures/Mar132024/featured_photo2.jpg",
    featured_photo_3: "/mscpictures/Mar132024/featured_photo3.jpg",
    featured_photo_4: "/mscpictures/Mar132024/featured_photo2.jpg",
    featured_photo_5: "/mscpictures/Mar132024/featured_photo3.jpg",
 },
 {
    id: 12,
    cover_image: "/mscpictures/Dec232024/featured_photo1.jpg",
    date: 'December 23, 2024',
    headline: 'Christmas Basket Project',
    description: `The MSC Mission Office Phils through the Task Force on Urban Conscientization (TFUC) conducted the 1st batch of Christmas Basket distribution in Brgy. Cupang, Antipolo last December 23, 2023. A total of 150 families benefited project. We would like to thank all our mission partners and donors who took part of this worthwhile project. `,
    hyperlink: '',
    featured_photo_2: "/mscpictures/Dec232024/featured_photo2.jpg",
    featured_photo_3: "/mscpictures/Dec232024/featured_photo3.jpg",
    featured_photo_4: "/mscpictures/Dec232024/featured_photo4.jpg",
    featured_photo_5: "/mscpictures/Dec232024/featured_photo5.jpg",
 },
 {
    id: 13,
    cover_image: "/mscpictures/Feb52024/featured_photo1.jpg",
    date: 'February 5, 2024',
    headline: 'Mindanao Flooding Mission Response',
    description: `Last February 5, 2024, the MSC Center for the Poor began its mission response to the flashflood affected families in Tagbina, Surigao del Sur. A total of 142 families have benefited the relief distribution. 
    There are more families who need assistance in different parts of Mindanao. The MSC Philippine Province through the MSC Mission Office is organizing another batch of Mission Response Project to the families who are greatly affected by flood in Talacogon and San Luis, Agusan del Sur.`,
    hyperlink: '',
    featured_photo_2: "/mscpictures/Feb52024/featured_photo2.jpg",
    featured_photo_3: "/mscpictures/Feb52024/featured_photo3.jpg",
    featured_photo_4: "/mscpictures/Feb52024/featured_photo4.jpg",
 }
]